CustomRange= 1 b1 e1 144680 2 b2 e2 MIDNIGHTBLUE 3 b3 e3 WHITE 4 b4 e4 WHITE 5 b5 e5 WHITE
TextColor=E8E8E8
TextBgColor=DARKBLUE
TextStyle=
DelimiterColor=WHEAT
DelimiterBgColor=
DelimiterStyle=
SpaceColor=GREEN
SpaceBgColor=
SpaceStyle=
NumberColor=DEEPSKYBLUE
NumberBgColor=
NumberStyle=
StringColor=RED
StringBgColor=
StringStyle=
CommentColor=Khaki
CommentBgColor=DarkSlateBlue
CommentStyle=
DirectiveColor=LIMEGREEN
DirectiveBgColor=
DirectiveStyle=
SpecialWordColor=DARKGOLDENROD
SpecialWordBgColor=
SpecialWordStyle=
LineNumberColor=MediumBlue
LineNumberBgColor=LightSteelBlue
LineNumberStyle=
ActiveLineColor=FUCHSIA
BookmarkColor=Cyan
BookmarkBgColor=DarkTurquoise
[1.Keyword]
Color=CYAN
BgColor=
Style=
[2.Keyword]
Color=LIGHTBLUE
BgColor=
Style= Bold
[3.Keyword]
Color=FORESTGREEN
BgColor=
Style= Bold
[4.Keyword]
Color=DARKORCHID
BgColor=
Style=
[5.Keyword]
Color=
BgColor=
Style=
[6.Keyword]
Color=GOLD
BgColor=
Style= Bold
[7.Keyword]
Color=Turquoise
BgColor=
Style=
[8.Keyword]
Color=DODGERBLUE
BgColor=
Style= Bold
[9.Keyword]
Color=BLACK
BgColor=
Style=
[a.Keyword]
Color=BLACK
BgColor=
Style=
