CustomRange= 1 b1 e1 404040 2 b2 e2 606060 3 b3 e3 808080 4 b4 e4 A0A0A0 5 b5 e5 WHITE
TextColor=E8E8E8
TextBgColor=BLACK
TextStyle=
DelimiterColor=WHEAT
DelimiterBgColor=
DelimiterStyle=
SpaceColor=GREEN
SpaceBgColor=
SpaceStyle=
NumberColor=DEEPSKYBLUE
NumberBgColor=
NumberStyle=
StringColor=RED
StringBgColor=
StringStyle=
CommentColor=PowderBlue
CommentBgColor=DarkSlateGray
CommentStyle=
DirectiveColor=CORNFLOWERBLUE
DirectiveBgColor=
DirectiveStyle=
SpecialWordColor=DARKGOLDENROD
SpecialWordBgColor=
SpecialWordStyle=
LineNumberColor=Linen
LineNumberBgColor=LightSlateGray
LineNumberStyle=
ActiveLineColor=FUCHSIA
BookmarkColor=DeepSkyBlue
BookmarkBgColor=MediumBlue
[1.Keyword]
Color=CYAN
BgColor=
Style=
[2.Keyword]
Color=LIGHTBLUE
BgColor=
Style= Bold
[3.Keyword]
Color=FORESTGREEN
BgColor=
Style= Bold
[4.Keyword]
Color=DARKORCHID
BgColor=
Style=
[5.Keyword]
Color=
BgColor=
Style=
[6.Keyword]
Color=GOLD
BgColor=
Style= Bold
[7.Keyword]
Color=Violet
BgColor=
Style=
[8.Keyword]
Color=INDIGO
BgColor=
Style= Bold
[9.Keyword]
Color=BLACK
BgColor=
Style=
[a.Keyword]
Color=BLACK
BgColor=
Style=
