CustomRange= 1 b1 e1 F0F0F0 2 b2 e2 E8E8E8 3 b3 e3 E0E0E0 4 b4 e4 D8D8D8 5 b5 e5 D0D0D0
TextColor=BLACK
TextBgColor=F8F8F8
TextStyle=
DelimiterColor=SADDLEBROWN
DelimiterBgColor=
DelimiterStyle=
SpaceColor=CYAN
SpaceBgColor=
SpaceStyle=
NumberColor=BLUE
NumberBgColor=
NumberStyle=
StringColor=RED
StringBgColor=
StringStyle=
CommentColor=TEAL
CommentBgColor=AZURE
CommentStyle=
DirectiveColor=GREEN
DirectiveBgColor=
DirectiveStyle=
SpecialWordColor=Navy
SpecialWordBgColor=
SpecialWordStyle=
LineNumberColor=WHITE
LineNumberBgColor=A0A0A0
LineNumberStyle=
ActiveLineColor=FUCHSIA
BookmarkColor=DeepSkyBlue
BookmarkBgColor=MediumBlue
[1.Keyword]
Color=DarkOrange
BgColor=
Style= Bold
[2.Keyword]
Color=DarkBlue
BgColor=
Style=Bold
[3.Keyword]
Color=ForestGreen
BgColor=
Style=Bold
[4.Keyword]
Color=DarkOrchid
BgColor=
Style=Bold
[5.Keyword]
Color=CornflowerBlue
BgColor=
Style=Bold
[6.Keyword]
Color=BLACK
BgColor=
Style=Bold
[7.Keyword]
Color=SlateGray
BgColor=
Style=
[8.Keyword]
Color=Indigo
BgColor=
Style=Bold
[9.Keyword]
Color=BLACK
BgColor=
Style=Bold
[a.Keyword]
Color=BLACK
BgColor=
Style=Bold
