// for xgettext
// misc
_("OK");
_("Cancel");
_("File '%s' already exists, do you really want to overwrite it?");
_("&Close");
_("&Goto...");
_("Goto Page");
_("Enter a page number between %d and %d:");
_("Please wait while printing\n");
_("Printing ");
_("All");
_("Bottom margin (mm):");
_("Copies:");
_("Default printer");
_("From:");
_("Landscape");
_("Left margin (mm):");
_("Orientation");
_("Page Setup");
_("Pages");
_("Paper Size");
_("Paper size");
_("Portrait");
_("PostScript file");
_("Print Range");
_("Print Setup");
_("Print in colour");
_("Print spooling");
_("Print to File");
_("Printer");
_("Printer command:");
_("Printer options");
_("Printer options:");
_("Printer...");
_("Printer:");
_("Right margin (mm):");
_("Setup...");
_("Status:");
_("To:");
_("Top margin (mm):");
_("Page %d of %d");
// syntax item
_("Text");
_("Delimiter");
_("Space");
_("Number");
_("String");
_("Comment");
_("Directive");
_("SpecialWord");
_("LineNumber");
_("ActiveLine");
_("Bookmark");
// HTML colors
_("AliceBlue");
_("AntiqueWhite");
_("Aqua");
_("Aquamarine");
_("Azure");
_("Beige");
_("Bisque");
_("Black");
_("BlanchedAlmond");
_("Blue");
_("BlueViolet");
_("Brown");
_("BurlyWood");
_("CadetBlue");
_("Chartreuse");
_("Chocolate");
_("Coral");
_("CornflowerBlue");
_("Cornsilk");
_("Crimson");
_("Cyan");
_("DarkBlue");
_("DarkCyan");
_("DarkGoldenRod");
_("DarkGray");
_("DarkGreen");
_("DarkKhaki");
_("DarkMagenta");
_("DarkOliveGreen");
_("DarkOrchid");
_("DarkRed");
_("DarkSalmon");
_("DarkSeaGreen");
_("DarkSlateBlue");
_("DarkSlateGray");
_("DarkTurquoise");
_("DarkViolet");
_("DarkOrange");
_("DeepPink");
_("DeepSkyBlue");
_("DimGray");
_("DodgerBlue");
_("Feldspar");
_("FireBrick");
_("FloralWhite");
_("ForestGreen");
_("Fuchsia");
_("Gainsboro");
_("GhostWhite");
_("Gold");
_("GoldenRod");
_("Gray");
_("Green");
_("GreenYellow");
_("HoneyDew");
_("HotPink");
_("IndianRed");
_("Indigo");
_("Ivory");
_("Khaki");
_("Lavender");
_("LavenderBlush");
_("LawnGreen");
_("LemonChiffon");
_("LightBlue");
_("LightCoral");
_("LightCyan");
_("LightGoldenRodYellow");
_("LightGreen");
_("LightGrey");
_("LightPink");
_("LightSalmon");
_("LightSeaGreen");
_("LightSkyBlue");
_("LightSlateBlue");
_("LightSlateGray");
_("LightSteelBlue");
_("LightYellow");
_("Lime");
_("LimeGreen");
_("Linen");
_("Magenta");
_("Maroon");
_("MediumAquaMarine");
_("MediumBlue");
_("MediumOrchid");
_("MediumPurple");
_("MediumSeaGreen");
_("MediumSlateBlue");
_("MediumSpringGreen");
_("MediumTurquoise");
_("MediumVioletRed");
_("MidnightBlue");
_("MintCream");
_("MistyRose");
_("Moccasin");
_("NavajoWhite");
_("Navy");
_("OldLace");
_("Olive");
_("OliveDrab");
_("Orange");
_("OrangeRed");
_("Orchid");
_("PaleGoldenRod");
_("PaleGreen");
_("PaleTurquoise");
_("PaleVioletRed");
_("PapayaWhip");
_("PeachPuff");
_("Peru");
_("Pink");
_("Plum");
_("PowderBlue");
_("Purple");
_("Red");
_("RosyBrown");
_("RoyalBlue");
_("SaddleBrown");
_("Salmon");
_("SandyBrown");
_("SeaGreen");
_("SeaShell");
_("Sienna");
_("Silver");
_("SkyBlue");
_("SlateBlue");
_("SlateGray");
_("Snow");
_("SpringGreen");
_("SteelBlue");
_("Tan");
_("Teal");
_("Thistle");
_("Tomato");
_("Turquoise");
_("Violet");
_("VioletRed");
_("Wheat");
_("White");
_("WhiteSmoke");
_("Yellow");
_("YellowGreen");
// syntax type
_("Plain Text");
_("AngelScript");
_("ASCII Art");
_("ASP(VBScript)");
_("awk");
_("C#");
_("C/C++");
_("CSS");
_("D");
_("diff/patch");
_("DOS Batch");
_("Flash ActionScript");
_("Fortran 90");
_("FreeBASIC");
_("HTML");
_("Java");
_("JavaScript");
_("JavaScript in HTML");
_("JSP");
_("Lua");
_("Pascal/Delphi");
_("Perl");
_("PHP");
_("Python");
_("Ruby");
_("SQL");
_("Squirrel");
_("TeX/LaTeX");
_("UNIX Configuration");
_("UNIX Shell Script");
_("Verilog");
_("VHDL");
_("Visual Basic");
_("Windows Registry File");
_("wxMEdit Syntax");
_("x86 Assembly");
_("XML");
