// for xgettext
_("Unicode 16 bit (UTF-16)")
_("Unicode 16 bit Big Endian (UTF-16BE)")
_("Unicode 16 bit Little Endian (UTF-16LE)")
_("Unicode 32 bit (UTF-32)")
_("Unicode 32 bit Big Endian (UTF-32BE)")
_("Unicode 32 bit Little Endian (UTF-32LE)")
_("Unicode 7 bit (UTF-7)")
_("Unicode 8 bit (UTF-8)")
_("Western European (ISO-8859-1)")
_("Central European (ISO-8859-2)")
_("Esperanto (ISO-8859-3)")
_("Baltic (old) (ISO-8859-4)")
_("Cyrillic (ISO-8859-5)")
_("Arabic (ISO-8859-6)")
_("Greek (ISO-8859-7)")
_("Hebrew (ISO-8859-8)")
_("Turkish (ISO-8859-9)")
_("Nordic (ISO-8859-10)")
_("Thai (ISO-8859-11)")
_("Indian (ISO-8859-12)")
_("Baltic (ISO-8859-13)")
_("Celtic (ISO-8859-14)")
_("Western European with Euro (ISO-8859-15)")
_("KOI8-R")
_("KOI8-U")
_("Windows Thai (CP 874)")
_("Windows Central European (CP 1250)")
_("Windows Cyrillic (CP 1251)")
_("Windows Western European (CP 1252)")
_("Windows Greek (CP 1253)")
_("Windows Turkish (CP 1254)")
_("Windows Hebrew (CP 1255)")
_("Windows Arabic (CP 1256)")
_("Windows Baltic (CP 1257)")
_("Windows Japanese (CP 932)")
_("Windows Chinese Simplified (CP 936)")
_("Windows Korean (CP 949)")
_("Windows Chinese Traditional (CP 950)")
_("Extended Unix Codepage for Japanese (EUC-JP)")
_("Windows/DOS OEM (CP 437)")
_("OK")
_("Cancel")
_("File '%s' already exists, do you really want to overwrite it?")
_("&Close")
_("&Goto...")
_("Goto Page")
_("Enter a page number between %d and %d:")
_("Please wait while printing\n")
_("Printing ")
_("All")
_("Bottom margin (mm):")
_("Copies:")
_("Default printer")
_("From:")
_("Landscape")
_("Left margin (mm):")
_("Orientation")
_("Page Setup")
_("Pages")
_("Paper Size")
_("Paper size")
_("Portrait")
_("PostScript file")
_("Print Range")
_("Print Setup")
_("Print in colour")
_("Print spooling")
_("Print to File")
_("Printer")
_("Printer command:")
_("Printer options")
_("Printer options:")
_("Printer...")
_("Printer:")
_("Right margin (mm):")
_("Setup...")
_("Status:")
_("To:")
_("Top margin (mm):")
